version: '3.3'
services:
  test:
    build:
      context: ./build_artifact/
    volumes:
      - ./artifact:/opt/artifact
  prod:
    image: tomcat:9.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./artifact:/usr/local/tomcat/webapps
    depends_on:
      - test