version: '3.3'
services:
  test:
    build:
      context: ./build_artifact/
    volumes:
      - app:/opt
  prod:
    image: tomcat:9.0-alpine
    ports:
      - "8080:8080"
    volumes:
      - app:/usr/local/tomcat/webapps:x
    depends_on:
      - test
volumes:
  app: