---
- name: build artefact
  hosts: build
  become: yes

  tasks:
  - name: install mvn
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - maven
        - openjdk-11-jdk
---