- name: build artefact
  hosts: build
  become: yes

  tasks:
  - name: install mvn
    apt:
      name: "{{ item }}"
    become: true
    loop:
        - maven
        - openjdk-11-jdk
        - wget
        - git