- name: build artefact
  hosts: build
  become: yes

  tasks:
  - name: install env
    apt:
      name: "{{ item }}"
    loop:
        - maven
        - openjdk-11-jdk
        - wget
        - git

  - name: build artefact
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /opt/
      clone: yes
      update: yes