- name: install env
  hosts: build
  become: yes

  tasks:
  - name: install java and mvn
    apt:
      name: "{{ item }}"
    loop:
        - maven
        - openjdk-11-jdk
        - wget
        - git

  - name: build artefact
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /opt/
      clone: yes
      update: yes

  - name: build artefact
    command: mvn -f /opt/pom.xml package

- name: deploy images and init
  hosts: prod
  become: yes

  tasks:
  - name: install tomcat9
    apt:
      name: "{{ item }}"
    loop:
      - tomcat9

  - name: Copy artifact
    synchronize: src=/opt/target/hello-1.0.war dest=/var/lib/tomcat9/webapps
    delegate_to: 172.20.0.19